name: Node.js CI

on:
  push:
    branches: ["main"]
    paths:
      - "03-Library/**"
  pull_request:
    branches: ["main"]
    paths:
      - "03-Library/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set Up Node.js
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies for project-one
        run: npm ci
        working-directory: ./03-Library

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: ./03-Library

      - name: Build project-one (if build script exists)
        run: npm run build --if-present
        working-directory: ./03-Library

      - name: Update config
        run: echo "export const settings = {host :\"http://localhost:3030\"}"  > 03-Library/src/config.js

      - name: Start BackEnd
        run: npm run start:be &
        working-directory: ./03-Library

      - name: Start FrontEnd
        run: npm run start:fe &
        working-directory: ./03-Library

      - name: Execute tests for project-one
        run: npm test
        working-directory: ./03-Library

  deploy-be:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_BE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}

  deploy-fe:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_FE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
